### ISSUE TITLE
Is this demo's admin functional?

### ISSUE THREAD

**Issue by shumiyao** [StaticJsCMS/static-cms-next-netlify-template#19]
I have tried this repo and `npm run develop` nicely but `npm run build`, `npm run start` then accessing to `http://localhost:3000/admin` with web browser causes the following error:

```
Uncaught SyntaxError: Identifier 'o' has already been declared (at 9ac0f527.d9feedd518643028.js:1197:685544)
```

Is this just me or known issue?

**Comment by shumiyao** [comment]
Update:

trying

```
 "next": "13.1.6",
```

seems to resolve the problem.

**Comment by KaneFreeman** [comment]
Okay the repo is reverted to Next 13.1.6 and I've added a cypress test to avoid this issue with future updates. Will investigate the Next issues as part of #20
