### ISSUE TITLE
npx create-next-app not working

### ISSUE THREAD

**Issue by aolchik** [StaticJsCMS/static-cms-next-netlify-template#36]
I'm trying to follow the instruction below to create an app from scratch, and the result is an empty directory.

I'm running OSX, node 19.0.1, npx 8.19.2

```
npx create-next-app your-blog --example "https://github.com/StaticJsCMS/static-cms-nextjs-netlify-blog-template"
```

**Comment by KaneFreeman** [comment]
Looks likes the URL was wrong in the README. Should be `https://github.com/StaticJsCMS/static-cms-next-netlify-template`

So the full command should be:

```
npx create-next-app your-blog --example "https://github.com/StaticJsCMS/static-cms-next-netlify-template"
```
